config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: :signout
  get 'welcome/about'
  get 'pages/saving_tips'
  get 'activities/index'

  resources :activities
  get 'log', to: 'activities#choose', as: :choose_activity
    #log_path("shower")
    #log_path("bath")
  get 'log/:activity_type', to: 'activities#new', as: :log
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  ACTIVITY_TYPES = %w(shower toilet bath)
  belongs_to :user
  validates :activity_type, presence: true, inclusion: {in: ACTIVITY_TYPES, allow_blank: true}
  validates :per_use, presence: true, numericality: { only_integer: true }
  validates :user, presence: true
  before_save :convert_to_oz
  
  #true = for high energy oz/gal
  #false = standard oz/gal
  #128 oz/gallon

  # def self.between(start_date, end_date)
  #   lambda {|start_date, end_date| where(created_at: (start_date.beginning_of_day...end_date.end_of_day))}.call(start_date, end_date)
  # end
  #need set var start_date end_date 
  scope :between, lambda {|start_date, end_date| where(created_at: (start_date.beginning_of_day...end_date.end_of_day))}
  
  CONVERSION_HASH = {
    true => {
      "shower" => 256,
      "toilet" => 256,
      "bath" => 5120
    },
    false => {
      "shower" => 512,
      "toilet" => 512,
      "bath" => 5120
    },
  }

  # def to_gallons
  #   per_day = self.ounces
  # end

  def self.today
    where("created_at >=?", Time.zone.now.beginning_of_day)
  end

  def log_notice
    if activity_type == "shower"
      "You took a #{per_use} minute #{activity_type}"
    elsif activity_type == "toilet"
      "You logged #{per_use} #{activity_type} flush"
    else activity_type == "bath"
      "You took #{per_use}  #{activity_type}"
    end
  end
  
  protected
    def convert_to_oz
      multiplier = CONVERSION_HASH[high_efficiency][activity_type]
      self.ounces = per_use * multiplier
    end
end

#extra
#validation for toilet, laundry, dishwasher
#Conversion hash for toilet, laundry, dishwasher
#add bath/faucets

app/models/user.rb
class User < ActiveRecord::Base
  has_many :activities
  validates :uid, presence: true
  validates :provider, presence: true, inclusion: {in: %w(twitter), allow_blank: true}
  
  def self.find_or_create_by_omniauth(auth_hash)
    # check to see if a user exists with the uid
    user = User.find_by(uid: auth_hash[:uid])
    # if it does, return that use
    if user.present?
      user
    else
    # if it doesnt, create the user with the providr, uid, info['name']
      create do |user|
      user.provider = (auth_hash[:provider])
      user.uid = (auth_hash[:uid])
      user.name = (auth_hash[:info][:name])
     end 
    end
  end
end

#extra to do
#Login with FB
#login without social media

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

 
  def index
    @activities = Activity.all
    if params[:start_date] && params[:end_date]
       @activities = current_user.activities.between(Date.strptime(params[:start_date], "%m/%d/%Y"), Date.strptime(params[:end_date], "%m/%d/%Y"))
      
     else
       @activities = Activity.today
     end
      @day_total  = Activity.today.sum(:ounces)/128
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      flash[:notice] = @activity.log_notice
      redirect_to choose_activity_path
    else
      flash[:error] = "No Activity logged"
      render :new
    end
  end



  
  # def create
  #   @user = current_user
  #   #wont work because not including high efficiency
  #   @activity = current_user.activities.today.find_or_initialize_by(activity_type: params[:activity][:activity_type])
  #   @activity.per_use = @activity.per_use.to_i + params[:activity][:per_use].to_i    
  #   if @activity.save
  #      flash[:notice] = @activity.log_notice
  #      redirect_to choose_activity_path
  #   else 
  #     flash[:notice] = "You did not log any activities"
  #     redirect_to choose_activity_path    
  #   end
  # end

  def show
    @activity = Activity.find(params[:id])
  end

  def choose
    @day_total  = Activity.today.sum(:ounces)/128
    @activities_by_type = current_user.activities.today.group(:activity_type).sum(:ounces) 
  end

  def update
  end


  def edit
    @activity = Activity.find(params[:id])
      flash[:notice] = "#{activity_type} log was updated"
  end

  private
    def activity_params
      params.require(:activity).permit(:per_use, :activity_type, :high_efficiency)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    #look up once
    @current_user ||= User.where(id: session[:user_id]).first if session[:user_id]
  end

  # make available w/i views


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def saving_tips
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path, notice: "Sign in Successful"
  end

  def destroy
    session.clear
    redirect_to root_path, notice: "Sign out Successful"
  end

  protected

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/choose.html.haml
%body.header-choose
.container
  .row
    .col-md-12
    %h3 Log Your Water Use

  .container.icon-margin
    .row
      .col-md-8
        .row
          - Activity::ACTIVITY_TYPES.each do |activity_type|
            .col-md-4
              .thumbnail-transp
              .container
              = link_to image_tag("activities/#{activity_type}.png"), log_path(activity_type)
              - if @activities_by_type[activity_type].present?
                #{@activities_by_type[activity_type]/128} gallons
              %br             
              /= link_to activity_type, log_path(activity_type)

      .col-md-4.text-margin
        %h5= "Water Usage Logged: #{Time.now.strftime("%m/%d/%Y")}"
        %h5= "Estimated Gallons Used: #{@day_total}"

app/views/activities/forms/_bath.html.haml
= form_for Activity.new do |f|
  = f.hidden_field :activity_type, :value => "bath"
  = f.label "Bath"
  = f.select(:per_use,(1..4))
  %p
  .form-group  
  = f.submit "Log Bath"
  = link_to "Back", :back
  

app/views/activities/forms/_shower.html.haml
= form_for Activity.new do |f|
  = f.hidden_field :activity_type, :value => "shower"
  = f.label "Shower"
  = f.select(:per_use,(2..15))
  = f.label "minutes"
  %p
  .form-group
  = f.label :high_efficiency
  = f.check_box :high_efficiency
  %p
  .form-group  
  = f.submit "Log Shower"
  %p
  = link_to "Back", :back

  

app/views/activities/forms/_toilet.html.haml
= form_for Activity.new do |f|
  = f.hidden_field :activity_type, :value => "toilet"
  = f.label "Toilet Flush"
  = f.select(:per_use,(1..10))
  %p
  .form-group
  = f.label :high_efficiency
  = f.check_box :high_efficiency
  %p
  = f.submit "Log Flush" 
  = link_to "Back", :back
  

app/views/activities/index.html.haml
%h4.align-center.blue Chart & Compare
.container
  .row
    .col-md-8
      %form.form-inline
        #date-range.input-group
          %input.form-control.date-picker{:type => "text", :name => "start_date"} 
          %span.input-group-addon to
          %input.form-control.date-picker{:type => "text", :name => "end_date"} 
          %span.input-group-addon
            %i.glyphicon.glyphicon-calendar
        .input-group
          %input.btn.btn-default{type: "submit", value: "Chart"}
.container
  .row
    .col-md-8
      - Activity::ACTIVITY_TYPES.each do |activity_type|
        .col-md-4

    .col-xs-6
  

  = column_chart @activities.group(:activity_type).sum("ounces/128")

  %h5 Gallons Used from #{params[:start_date]} to  #{params[:end_date]}
  
  %h5= "Total Estimated Gallons Used: #{@activities.group(:activity_type).sum("ounces/128")}"

  
  /= column_chart @activities.map { |c| [c.sum_of_gallons, c.created_at_date] }

/   Activity.select("SUM(ounces)/128 as sum_of_gallons

/   Activity.between(2.days.ago, 1.hour.ago).select("SUM(ounces)/128 as sum_of_gallons, DATE(activities.created_at) as created_at_date").group("DATE(activities.created_at)").order("sum_of_gallons")

/ Activity.between(4.days.ago, Time.now).select("SUM(ounces)/128 as sum_of_gallons, DATE(activities.created_at) as created_at_date").group("DATE(activities.created_at)").order("sum_of_gallons")

app/views/activities/new.html.haml
.container
  %h4 Log Water Use
  .container
  %p
    = render partial: "activities/forms/#{params[:activity_type]}"


/how do i save without submitting? => new view with form and redirect
/how can i change "shower label" to image/icon?
/why do i want the "shower" label hidden?

app/views/activities/show.html.haml
%h1 Activity#show
%p Find me in app/views/activity/show.html.haml

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#main-nav", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand KnoWater
    / Collect the nav links, forms, and other content for toggling
    #main-nav.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "/welcome/about"}
            About
            %span.sr-only (current)
        %li
          %a{:href => "/"}
            Home
            %span.sr-only (current)
        %li
          %a{:href => "/pages/saving_tips"}
            Saving Tips
            %span.sr-only(current)
        %li
          %a{:href => "/activities/index"}
            Compare
            %span.sr-only(current)            
        %li
          %a{:href => "/log"}
            Log
            %span.sr-only(current)

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %p.navbar-text.navbar-right
            Hello #{current_user.name} !
            = link_to 'Sign out', signout_path
        - else
          %p.navbar-right
            = link_to "/auth/twitter", class: 'btn btn-social btn-lg btn-twitter btn-sm', role: 'button', style: "margin-top: 10px;" do
              %i.fa.fa-twitter &nbsp;
              Sign in with Twitter
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %link{:href => "http://fonts.googleapis.com/css?family=Nixie+One", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Ledger", :rel => "stylesheet", :type => "text/css"}/
    = javascript_include_tag "http://www.google.com/jsapi", "chartkick"
    
    %title Knowater
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "layouts/nav"
    /render partial ?
    .container
      -if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"}
          =flash[:notice]

      -elsif flash[:error]
        .alert.alert-danger
          %button.close{"data-dismiss" => "alert", :type => "button"}
          =flash[:error]

      -elsif flash[:alert]
        .alert 
          %button.close{"data-dismiss" => "alert", :type => "button"}
          =flash[:alert]

  =  yield

app/views/pages/saving_tips.html.haml
%body.header-saving
.container
  .row
    .col-md-8
      .jumbotron-transp
        %h3
          Water saving ideas:
        %p
          KnoWater is just the beginning. To learn more, visit some of these water conservation websites:
        %p
          Water Use it Wisely: 
          =link_to 'Water Use It Wisely', 'http://www.wateruseitwisely.com'
          (Arizona)
        %p
          Be Water Wise: 
          =link_to 'Be Water Wise', 'http://www.bewaterwise.com' 
          (Southern California)
        %p
          East Bay Municipal Water District: 
          =link_to 'Conservation Tips', 'https://www.ebmud.com/water-and-drought/conservation-and-rebates'
          (Northern California)
        %p
          Green Building:
          =link_to 'Environmental Protection Agency', 'ConserveWater.htm'
        %p
          National Geographic:
          =link_to 'National Geographic - When Snow Fails', 'http://www.nationalgeographic.com/west-snow-fail/' 
          (California Drought)
        %p
          Water Saving Information
          KnoWater reminds you that water conservation takes all forms.  The are simple actions you can take in your home, at your work place and in your community that can have dramatically positive consequences.  For example:
        %p          
          Short showers are better than baths, but WaterSense labeled faucets and appliances make a greater impact long-term
        %p
          Save by NOT watering your lawn in the hottest part of the day, or consider drought-resistant plants and a drip system to save even more.
          Carry a reusable water bottle.  It's healthier, and the amount of water to MAKE disposable plastic bottles is significant
        / %p
        /   For 97 more ideas, visit 
        /   =link_to 'WaterUseItWisely', 'http://www.WaterUseItWisely.com'

  / .row
  /   .col-md-12
  /     %h4 Links to more information
  /     %iframe{:frameborder => "0", :height => "285", :name => "wuiw-water-saving-tips", :scrolling => "no", :src => "http://wateruseitwisely.com/widget/", :width => "151"} Visit Wateruseitwisely.com/100-ways-to-conserve for water-saving tips!

app/views/welcome/about.html.haml
%h3.center Why Knowater
.container
  %p 
    Born out of the crippling California drought in 2015, KnoWater is a resource for families to get to know their water better. If you like what you've learned, and are taking steps to conserve water, we want to hear about it.  (Contact info.)

  %p
    v1.0.0 - current version of the application uses standard appliances and faucets to calculate gallon amounts. 
  %p
    next release will offer the option to select/set high efficiency options

  %p
    Thank you to https://icons8.com/ for use of their icons

app/views/welcome/index.html.haml
%body.header-bg
  .container.center
  .container
    .row
    .col-md-12
      .jumbotron-transp
        %h1 KnoWater
        %h3.blue.align-center Make a Difference
        %p The average American uses more than 100 gallons of water daily   
        %p Do you know how much water you currently use?  
        %p
          %li
            Use the 
            =link_to "Log", choose_activity_path
            to Track your daily usage
          %li 
            Make little changes to 
            =link_to "Save Water", pages_saving_tips_path 
          %li Pledge to Reduce 10% or even more
          %li 
            =link_to "Compare", activities_index_path 
            Past Use to Current Use


      .col-md-8.jumbotron-transp.margin-left
        %ul.list-unstyled
          %i.fa.fa-quote-left.fa-2x.pull-left
          %h4 We never know the worth of water till the well is dry. 
          %h5 ~Thomas Fuller, Gnomologia, 1732

          / %li.mbottom
          /   = link_to "/auth/twitter", class: 'btn btn-social btn-lg btn-twitter btn-sm', role: 'button' do
          /     %i.fa.fa-twitter &nbsp;
          /     Sign in with Twitter
        / %li
        /   = link_to "#", class: 'btn btn-social btn-lg btn-facebook btn-sm', role: 'button' do
        /     %i.fa.fa-twitter &nbsp;
        /     Sign in with Facebook

   


     





/%h1 Do you Know Water?
/ %p Find me in app/views/welcome/index.html.haml
/ .col-sm-5
/   %p Sign in using social media
/   %p   
/     %a.btn.btn-social.btn-lg.btn-twitter{:href => "/auth/twitter", :role => "button"} 
/       %i.fa.fa-twitter &nbsp;
/       Sign in with Twitter